from .user import User
from .chat import Chat
from .chat_full_info import ChatFullInfo
from .message import Message
from .message_id import MessageId
from .inaccessible_message import InaccessibleMessage
from .message_entity import MessageEntity
from .text_quote import TextQuote
from .external_reply_info import ExternalReplyInfo
from .reply_parameters import ReplyParameters
from .message_origin_user import MessageOriginUser
from .message_origin_hidden_user import MessageOriginHiddenUser
from .message_origin_chat import MessageOriginChat
from .message_origin_channel import MessageOriginChannel
from .photo_size import PhotoSize
from .animation import Animation
from .audio import Audio
from .document import Document
from .story import Story
from .video import Video
from .video_note import VideoNote
from .voice import Voice
from .paid_media_info import PaidMediaInfo
from .paid_media_preview import PaidMediaPreview
from .paid_media_photo import PaidMediaPhoto
from .paid_media_video import PaidMediaVideo
from .contact import Contact
from .dice import Dice
from .poll_option import PollOption
from .input_poll_option import InputPollOption
from .poll_answer import PollAnswer
from .poll import Poll
from .location import Location
from .venue import Venue
from .web_app_data import WebAppData
from .proximity_alert_triggered import ProximityAlertTriggered
from .message_auto_delete_timer_changed import MessageAutoDeleteTimerChanged
from .chat_boost_added import ChatBoostAdded
from .background_fill import BackgroundFill
from .background_fill_solid import BackgroundFillSolid
from .background_fill_gradient import BackgroundFillGradient
from .background_fill_freeform_gradient import BackgroundFillFreeformGradient
from .background_type import BackgroundType
from .background_type_fill import BackgroundTypeFill
from .background_type_wallpaper import BackgroundTypeWallpaper
from .background_type_pattern import BackgroundTypePattern
from .background_type_chat_theme import BackgroundTypeChatTheme
from .chat_background import ChatBackground
from .forum_topic_created import ForumTopicCreated
from .forum_topic_edited import ForumTopicEdited
from .shared_user import SharedUser
from .users_shared import UsersShared
from .chat_shared import ChatShared
from .write_access_allowed import WriteAccessAllowed
from .video_chat_scheduled import VideoChatScheduled
from .video_chat_ended import VideoChatEnded
from .video_chat_participants_invited import VideoChatParticipantsInvited
from .paid_message_price_changed import PaidMessagePriceChanged
from .giveaway_created import GiveawayCreated
from .giveaway import Giveaway
from .giveaway_winners import GiveawayWinners
from .giveaway_completed import GiveawayCompleted
from .link_preview_options import LinkPreviewOptions
from .user_profile_photos import UserProfilePhotos
from .file import File
from .web_app_info import WebAppInfo
from .reply_keyboard_markup import ReplyKeyboardMarkup
from .keyboard_button import KeyboardButton
from .keyboard_button_request_users import KeyboardButtonRequestUsers
from .keyboard_button_request_chat import KeyboardButtonRequestChat
from .keyboard_button_poll_type import KeyboardButtonPollType
from .reply_keyboard_remove import ReplyKeyboardRemove
from .inline_keyboard_markup import InlineKeyboardMarkup
from .inline_keyboard_button import InlineKeyboardButton
from .login_url import LoginUrl
from .switch_inline_query_chosen_chat import SwitchInlineQueryChosenChat
from .copy_text_button import CopyTextButton
from .callback_query import CallbackQuery
from .force_reply import ForceReply
from .chat_photo import ChatPhoto
from .chat_invite_link import ChatInviteLink
from .chat_administrator_rights import ChatAdministratorRights
from .chat_member_updated import ChatMemberUpdated
from .chat_member_owner import ChatMemberOwner
from .chat_member_administrator import ChatMemberAdministrator
from .chat_member_member import ChatMemberMember
from .chat_member_restricted import ChatMemberRestricted
from .chat_member_left import ChatMemberLeft
from .chat_member_banned import ChatMemberBanned
from .chat_join_request import ChatJoinRequest
from .chat_permissions import ChatPermissions
from .birthdate import Birthdate
from .business_intro import BusinessIntro
from .business_location import BusinessLocation
from .business_opening_hours_interval import BusinessOpeningHoursInterval
from .business_opening_hours import BusinessOpeningHours
from .story_area_position import StoryAreaPosition
from .location_address import LocationAddress
from .story_area_type_location import StoryAreaTypeLocation
from .story_area_type_suggested_reaction import StoryAreaTypeSuggestedReaction
from .story_area_type_link import StoryAreaTypeLink
from .story_area_type_weather import StoryAreaTypeWeather
from .story_area_type_unique_gift import StoryAreaTypeUniqueGift
from .story_area import StoryArea
from .chat_location import ChatLocation
from .reaction_type_emoji import ReactionTypeEmoji
from .reaction_type_custom_emoji import ReactionTypeCustomEmoji
from .reaction_type_paid import ReactionTypePaid
from .reaction_count import ReactionCount
from .message_reaction_updated import MessageReactionUpdated
from .message_reaction_count_updated import MessageReactionCountUpdated
from .forum_topic import ForumTopic
from .gift import Gift
from .gifts import Gifts
from .unique_gift_model import UniqueGiftModel
from .unique_gift_symbol import UniqueGiftSymbol
from .unique_gift_backdrop_colors import UniqueGiftBackdropColors
from .unique_gift_backdrop import UniqueGiftBackdrop
from .unique_gift import UniqueGift
from .gift_info import GiftInfo
from .unique_gift_info import UniqueGiftInfo
from .owned_gift_regular import OwnedGiftRegular
from .owned_gift_unique import OwnedGiftUnique
from .owned_gifts import OwnedGifts
from .accepted_gift_types import AcceptedGiftTypes
from .star_amount import StarAmount
from .bot_command import BotCommand
from .bot_command_scope_default import BotCommandScopeDefault
from .bot_command_scope_all_private_chats import BotCommandScopeAllPrivateChats
from .bot_command_scope_all_group_chats import BotCommandScopeAllGroupChats
from .bot_command_scope_all_chat_administrators import BotCommandScopeAllChatAdministrators
from .bot_command_scope_chat import BotCommandScopeChat
from .bot_command_scope_chat_administrators import BotCommandScopeChatAdministrators
from .bot_command_scope_chat_member import BotCommandScopeChatMember
from .bot_name import BotName
from .bot_description import BotDescription
from .bot_short_description import BotShortDescription
from .menu_button_commands import MenuButtonCommands
from .menu_button_web_app import MenuButtonWebApp
from .menu_button_default import MenuButtonDefault
from .chat_boost_source_premium import ChatBoostSourcePremium
from .chat_boost_source_gift_code import ChatBoostSourceGiftCode
from .chat_boost_source_giveaway import ChatBoostSourceGiveaway
from .chat_boost import ChatBoost
from .chat_boost_updated import ChatBoostUpdated
from .chat_boost_removed import ChatBoostRemoved
from .user_chat_boosts import UserChatBoosts
from .business_bot_rights import BusinessBotRights
from .business_connection import BusinessConnection
from .business_messages_deleted import BusinessMessagesDeleted
from .response_parameters import ResponseParameters
from .input_media_photo import InputMediaPhoto
from .input_media_video import InputMediaVideo
from .input_media_animation import InputMediaAnimation
from .input_media_audio import InputMediaAudio
from .input_media_document import InputMediaDocument
from .input_paid_media_photo import InputPaidMediaPhoto
from .input_paid_media import InputPaidMedia
from .input_paid_media_video import InputPaidMediaVideo
from .input_profile_photo_static import InputProfilePhotoStatic
from .input_profile_photo_animated import InputProfilePhotoAnimated
from .input_story_content_photo import InputStoryContentPhoto
from .input_story_content_video import InputStoryContentVideo