from typing import Union, List, Optional
from pydantic import BaseModel
from .dice import Dice
from ..stickers import Sticker
from .contact import Contact
from .document import Document
from ..payments import Invoice
from .message_origin import MessageOrigin
from .animation import Animation
from .venue import Venue
from .video_note import VideoNote
from .photo_size import PhotoSize
from .location import Location
from .giveaway import Giveaway
from .giveaway_winners import GiveawayWinners
from .poll import Poll
from .paid_media_info import PaidMediaInfo
from .chat import Chat
from .link_preview_options import LinkPreviewOptions
from .voice import Voice
from ..games import Game
from .video import Video
from .audio import Audio
from .story import Story

class ExternalReplyInfo(BaseModel):
    origin: MessageOrigin
    chat: Optional[Chat] = None
    message_id: Optional[int] = None
    link_preview_options: Optional[LinkPreviewOptions] = None
    animation: Optional[Animation] = None
    audio: Optional[Audio] = None
    document: Optional[Document] = None
    paid_media: Optional[PaidMediaInfo] = None
    photo: Optional[List[PhotoSize]] = None
    sticker: Optional[Sticker] = None
    story: Optional[Union[Story]] = None
    video: Optional[Video] = None
    video_note: Optional[VideoNote] = None
    voice: Optional[Voice] = None
    has_media_spoiler: Optional[bool] = None
    contact: Optional[Contact] = None
    dice: Optional[Dice] = None
    game: Optional[Game] = None
    giveaway: Optional[Giveaway] = None
    giveaway_winners: Optional[GiveawayWinners] = None
    invoice: Optional[Invoice] = None
    location: Optional[Location] = None
    poll: Optional[Poll] = None
    venue: Optional[Venue] = None