from typing import Union, List, Optional, Self
from pydantic import BaseModel, Field
from .dice import Dice
from .general_forum_topic_unhidden import GeneralForumTopicUnhidden
from ..stickers import Sticker
from .video_chat_participants_invited import VideoChatParticipantsInvited
from .chat_background import ChatBackground
from ..payments import RefundedPayment
from .contact import Contact
from .document import Document
from .maybe_inaccessible_message import MaybeInaccessibleMessage
from .proximity_alert_triggered import ProximityAlertTriggered
from .write_access_allowed import WriteAccessAllowed
from .giveaway_completed import GiveawayCompleted
from .general_forum_topic_hidden import GeneralForumTopicHidden
from ..payments import Invoice
from .animation import Animation
from .message_origin import MessageOrigin
from .gift_info import GiftInfo
from .video_chat_started import VideoChatStarted
from .venue import Venue
from .video_note import VideoNote
from .photo_size import PhotoSize
from .video_chat_ended import VideoChatEnded
from .location import Location
from .giveaway import Giveaway
from .forum_topic_created import ForumTopicCreated
from .giveaway_winners import GiveawayWinners
from .forum_topic_closed import ForumTopicClosed
from .chat_boost_added import ChatBoostAdded
from .external_reply_info import ExternalReplyInfo
from .poll import Poll
from .user import User
from .unique_gift_info import UniqueGiftInfo
from .paid_media_info import PaidMediaInfo
from .web_app_data import WebAppData
from .forum_topic_edited import ForumTopicEdited
from .chat import Chat
from .link_preview_options import LinkPreviewOptions
from .voice import Voice
from ..games import Game
from ..payments import SuccessfulPayment
from .giveaway_created import GiveawayCreated
from .chat_shared import ChatShared
from .video import Video
from .message_entity import MessageEntity
from ..tgpassport import PassportData
from .video_chat_scheduled import VideoChatScheduled
from .audio import Audio
from .story import Story
from .text_quote import TextQuote
from .message_auto_delete_timer_changed import MessageAutoDeleteTimerChanged
from .forum_topic_reopened import ForumTopicReopened
from .inline_keyboard_markup import InlineKeyboardMarkup
from .paid_message_price_changed import PaidMessagePriceChanged
from .users_shared import UsersShared

class Message(BaseModel):
    message_id: int
    message_thread_id: Optional[int] = None
    user: Optional[User] = Field(alias="from", default=None)
    sender_chat: Optional[Chat] = None
    sender_boost_count: Optional[int] = None
    sender_business_bot: Optional[User] = None
    date: int
    business_connection_id: Optional[str] = None
    chat: Chat
    forward_origin: Optional[MessageOrigin] = None
    is_topic_message: Optional[bool] = None
    is_automatic_forward: Optional[bool] = None
    reply_to_message: Optional[Message] = None
    external_reply: Optional[ExternalReplyInfo] = None
    quote: Optional[TextQuote] = None
    reply_to_story: Optional[Union[Story]] = None
    via_bot: Optional[User] = None
    edit_date: Optional[int] = None
    has_protected_content: Optional[bool] = None
    is_from_offline: Optional[bool] = None
    media_group_id: Optional[str] = None
    author_signature: Optional[str] = None
    paid_star_count: Optional[int] = None
    text: Optional[str] = None
    entities: Optional[List[MessageEntity]] = None
    link_preview_options: Optional[LinkPreviewOptions] = None
    effect_id: Optional[str] = None
    animation: Optional[Animation] = None
    audio: Optional[Audio] = None
    document: Optional[Document] = None
    paid_media: Optional[PaidMediaInfo] = None
    photo: Optional[List[PhotoSize]] = None
    sticker: Optional[Sticker] = None
    story: Optional[Union[Story]] = None
    video: Optional[Video] = None
    video_note: Optional[VideoNote] = None
    voice: Optional[Voice] = None
    caption: Optional[str] = None
    caption_entities: Optional[List[MessageEntity]] = None
    show_caption_above_media: Optional[bool] = None
    has_media_spoiler: Optional[bool] = None
    contact: Optional[Contact] = None
    dice: Optional[Dice] = None
    game: Optional[Game] = None
    poll: Optional[Poll] = None
    venue: Optional[Venue] = None
    location: Optional[Location] = None
    new_chat_members: Optional[List[User]] = None
    left_chat_member: Optional[User] = None
    new_chat_title: Optional[str] = None
    new_chat_photo: Optional[List[PhotoSize]] = None
    delete_chat_photo: Optional[bool] = None
    group_chat_created: Optional[bool] = None
    supergroup_chat_created: Optional[bool] = None
    channel_chat_created: Optional[bool] = None
    message_auto_delete_timer_changed: Optional[MessageAutoDeleteTimerChanged] = None
    migrate_to_chat_id: Optional[int] = None
    migrate_from_chat_id: Optional[int] = None
    pinned_message: Optional[MaybeInaccessibleMessage] = None
    invoice: Optional[Invoice] = None
    successful_payment: Optional[SuccessfulPayment] = None
    refunded_payment: Optional[RefundedPayment] = None
    users_shared: Optional[UsersShared] = None
    chat_shared: Optional[ChatShared] = None
    gift: Optional[GiftInfo] = None
    unique_gift: Optional[UniqueGiftInfo] = None
    connected_website: Optional[str] = None
    write_access_allowed: Optional[WriteAccessAllowed] = None
    passport_data: Optional[Union[PassportData]] = None
    proximity_alert_triggered: Optional[ProximityAlertTriggered] = None
    boost_added: Optional[ChatBoostAdded] = None
    chat_background_set: Optional[ChatBackground] = None
    forum_topic_created: Optional[Union[ForumTopicCreated]] = None
    forum_topic_edited: Optional[Union[ForumTopicEdited]] = None
    forum_topic_closed: Optional[Union[ForumTopicClosed]] = None
    forum_topic_reopened: Optional[Union[ForumTopicReopened]] = None
    general_forum_topic_hidden: Optional[Union[GeneralForumTopicHidden]] = None
    general_forum_topic_unhidden: Optional[Union[GeneralForumTopicUnhidden]] = None
    giveaway_created: Optional[GiveawayCreated] = None
    giveaway: Optional[Giveaway] = None
    giveaway_winners: Optional[GiveawayWinners] = None
    giveaway_completed: Optional[GiveawayCompleted] = None
    paid_message_price_changed: Optional[PaidMessagePriceChanged] = None
    video_chat_scheduled: Optional[VideoChatScheduled] = None
    video_chat_started: Optional[VideoChatStarted] = None
    video_chat_ended: Optional[VideoChatEnded] = None
    video_chat_participants_invited: Optional[VideoChatParticipantsInvited] = None
    web_app_data: Optional[WebAppData] = None
    reply_markup: Optional[InlineKeyboardMarkup] = None