from .base import TelegramAPIMethod
from .get_me import GetMe
from .log_out import LogOut
from .close import Close
from .send_message import SendMessage
from .forward_message import ForwardMessage
from .forward_messages import ForwardMessages
from .copy_message import CopyMessage
from .copy_messages import CopyMessages
from .send_photo import SendPhoto
from .send_audio import SendAudio
from .send_document import SendDocument
from .send_video import SendVideo
from .send_animation import SendAnimation
from .send_voice import SendVoice
from .send_video_note import SendVideoNote
from .send_paid_media import SendPaidMedia
from .send_media_group import SendMediaGroup
from .send_location import SendLocation
from .send_venue import SendVenue
from .send_contact import SendContact
from .send_poll import SendPoll
from .send_dice import SendDice
from .send_chat_action import SendChatAction
from .set_message_reaction import SetMessageReaction
from .get_user_profile_photos import GetUserProfilePhotos
from .set_user_emoji_status import SetUserEmojiStatus
from .get_file import GetFile
from .ban_chat_member import BanChatMember
from .unban_chat_member import UnbanChatMember
from .restrict_chat_member import RestrictChatMember
from .promote_chat_member import PromoteChatMember
from .set_chat_administrator_custom_title import SetChatAdministratorCustomTitle
from .ban_chat_sender_chat import BanChatSenderChat
from .unban_chat_sender_chat import UnbanChatSenderChat
from .set_chat_permissions import SetChatPermissions
from .export_chat_invite_link import ExportChatInviteLink
from .create_chat_invite_link import CreateChatInviteLink
from .edit_chat_invite_link import EditChatInviteLink
from .create_chat_subscription_invite_link import CreateChatSubscriptionInviteLink
from .edit_chat_subscription_invite_link import EditChatSubscriptionInviteLink
from .revoke_chat_invite_link import RevokeChatInviteLink
from .approve_chat_join_request import ApproveChatJoinRequest
from .decline_chat_join_request import DeclineChatJoinRequest
from .set_chat_photo import SetChatPhoto
from .delete_chat_photo import DeleteChatPhoto
from .set_chat_title import SetChatTitle
from .set_chat_description import SetChatDescription
from .pin_chat_message import PinChatMessage
from .unpin_chat_message import UnpinChatMessage
from .unpin_all_chat_messages import UnpinAllChatMessages
from .leave_chat import LeaveChat
from .get_chat import GetChat
from .get_chat_administrators import GetChatAdministrators
from .get_chat_member_count import GetChatMemberCount
from .get_chat_member import GetChatMember
from .set_chat_sticker_set import SetChatStickerSet
from .delete_chat_sticker_set import DeleteChatStickerSet
from .get_forum_topic_icon_stickers import GetForumTopicIconStickers
from .create_forum_topic import CreateForumTopic
from .edit_forum_topic import EditForumTopic
from .close_forum_topic import CloseForumTopic
from .reopen_forum_topic import ReopenForumTopic
from .delete_forum_topic import DeleteForumTopic
from .unpin_all_forum_topic_messages import UnpinAllForumTopicMessages
from .edit_general_forum_topic import EditGeneralForumTopic
from .close_general_forum_topic import CloseGeneralForumTopic
from .reopen_general_forum_topic import ReopenGeneralForumTopic
from .hide_general_forum_topic import HideGeneralForumTopic
from .unhide_general_forum_topic import UnhideGeneralForumTopic
from .unpin_all_general_forum_topic_messages import UnpinAllGeneralForumTopicMessages
from .answer_callback_query import AnswerCallbackQuery
from .get_user_chat_boosts import GetUserChatBoosts
from .get_business_connection import GetBusinessConnection
from .set_my_commands import SetMyCommands
from .delete_my_commands import DeleteMyCommands
from .get_my_commands import GetMyCommands
from .set_my_name import SetMyName
from .get_my_name import GetMyName
from .set_my_description import SetMyDescription
from .get_my_description import GetMyDescription
from .set_my_short_description import SetMyShortDescription
from .get_my_short_description import GetMyShortDescription
from .set_chat_menu_button import SetChatMenuButton
from .get_chat_menu_button import GetChatMenuButton
from .set_my_default_administrator_rights import SetMyDefaultAdministratorRights
from .get_my_default_administrator_rights import GetMyDefaultAdministratorRights