from typing import Union
from .input_location_message_content import InputLocationMessageContent
from .input_contact_message_content import InputContactMessageContent
from .input_venue_message_content import InputVenueMessageContent
from .input_invoice_message_content import InputInvoiceMessageContent
from .input_text_message_content import InputTextMessageContent

InputMessageContent = Union[InputTextMessageContent, InputLocationMessageContent, InputVenueMessageContent, InputContactMessageContent, InputInvoiceMessageContent]